extend type Query {
    tagGroups(rubric: String): [TagGroup!]! @field(resolver: "App\\GraphQL\\Queries\\TagGroups")
}

extend type Mutation {
    updateTag(input: UpdateTagInput!): Tag! @guard @field(resolver: "App\\GraphQL\\Mutations\\UpdateTag")
    deleteTag(id: ID!): Tag! @guard @field(resolver: "App\\GraphQL\\Mutations\\DeleteTag")
    createTag(input: CreateTagInput!): Tag! @guard @field(resolver: "App\\GraphQL\\Mutations\\CreateTag")
}

type TagGroup {
    id: ID!
    slug: String!
    name: String!
    tags: [Tag!]!
}

type Tag {
    id: ID!
    name: String!
    tag_group_id: ID!
    href: String
    managed: Boolean
    group: TagGroup!
}

input CreateTagInput {
    tag_group_id: ID!
    name: String!
}

input UpdateTagInput {
    id: ID!
    name: String!
}
